/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    SearchInput: typeof import('./src/components/SearchInput.vue')['default']
    Sort: typeof import('./src/components/Sort.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TableHeader: typeof import('./src/components/TableHeader.vue')['default']
    TablePagination: typeof import('./src/components/TablePagination.vue')['default']
    TeamPagination: typeof import('./src/components/TeamPagination.vue')['default']
  }
}
